---
title: "Assignment 10"
author: "Vishal"
date: "2022-12-07"
output: html_document
---

```{r setup, include=FALSE, warning=F, message=F}
knitr::opts_chunk$set(echo = TRUE)
```

#1. Linear discriminant analysis
```{r}
library(Stat2Data) 
library(tidyverse)
data(Hawks)
library(MASS)
```

```{r}
hawks_total <- Hawks %>% 
  select( Weight, Wing, Hallux, Tail, Species) %>% 
  filter(Species =='SS' | Species =='CH') %>% drop_na() %>% 
  mutate(Species = as.numeric(Species =='SS'))

hawks_total
```
```{r}
num_total <- hawks_total %>% nrow() 
num_train <- floor(num_total*0.6) 
num_test <- num_total-num_train 
set.seed(0) 
test_inds <- sample(seq(num_total),num_test) 
train_inds <- setdiff(seq(num_total),test_inds) 
hawks_train <- hawks_total %>% 
  filter(row_number() %in% train_inds) 

hawks_test <- hawks_total %>%  filter(row_number() %in% test_inds) 
```


```{r}
hawks_train_x <- hawks_train %>% select(-Species)
hawks_train_y <- hawks_train %>% pull(Species)

hawks_test_x <- hawks_test %>% select(-Species)
hawks_test_y <- hawks_test %>% pull(Species)
```

```{r}
lda_model <- MASS::lda(Species ~ ., hawks_train)
```

```{r}
lda_train_predicted_y <- predict(lda_model, hawks_train_x)$class %>%
  as.character() %>% as.numeric()

lda_train_error <- mean(abs(lda_train_predicted_y - hawks_train_y))
lda_train_error
```
```{r}
lda_test_predicted_y <- predict(lda_model, hawks_test_x)$class %>%
  as.character() %>% as.numeric()

lda_test_error <- mean(abs(lda_test_predicted_y - hawks_test_y))
lda_test_error
```















































